name = "Hackers Modpack"
author = "Fahim H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4569c0ee07369e5c757da3eda8f38533f63fe1cd2baa6cfe34c1e18c920cf6b"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
